### ISSUE TITLE
ask a question about the 'net.mat'

### ISSUE THREAD

**Issue by GY5134** [mahmoudnafifi/Semantic-Color-Constancy-Using-CNN#2]
Dear researcher, I am sorry to disturb you, when debugging your code, there is a missing'net.mat', I don't know, what is the role of this net? Where can I get the file? Hope to get your reply!

**Comment by mahmoudnafifi** [comment]
Hi,
You should download the trained model from here to use the testing code: 
https://drive.google.com/open?id=0B6CktEG1p54WVVpyMlhOMjBjZk0

**Comment by zeinab89** [comment]
I have the same problem about missing "net.mat".
In addition, I have no access to the address, "https://drive.google.com/open?id=0B6CktEG1p54WVVpyMlhOMjBjZk0" that you mentioned in your reply. 
How can I have the trained model 'net.mat'?
I hope to hear from you soon
Thank you for your attention in advance

**Comment by mahmoudnafifi** [comment]
Please try this link:
https://drive.google.com/file/d/0B6CktEG1p54WVVpyMlhOMjBjZk0/view?usp=sharing&resourcekey=0-F3-dFS8yWTq8G0chYu2Lvg

**Comment by zeinab89** [comment]
> Please try this link: https://drive.google.com/file/d/0B6CktEG1p54WVVpyMlhOMjBjZk0/view?usp=sharing&resourcekey=0-F3-dFS8yWTq8G0chYu2Lvg

Thank you
